server:
  port: 8989

spring:
  cloud:
    gateway:
      routes:
        - id: driver
          uri: lb://driver
          predicates:
            - Path=/services/**
          filters:
            - name: CircuitBreaker
              args:
                name: driver
                fallbackuri: forward:/driverFallBack
        - id: email
          uri: lb://email
          predicates:
            - Path=/services/**
          filters:
            - name: CircuitBreaker
              args:
                name: email
                fallbackuri: forward:/emailFallback


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
