#version: "3"
#services:
#  discovery-server:
#    image: auth-server
#    ports:
#      - 9191:9191
#


version: "3"
services:

  menu:
    image: mysql
    networks:
      - menu-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=vehiclepasser_auth

  menu-jdbc:
    image: auth-server
    ports:
      - "9191:9191"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://menu:3306/vehiclepasser_auth
    networks:
      - menu-mysql
    depends_on:
      - menu
networks:
  menu-mysql:





























