server:
  port: 9192
  error:
    include-message: always
spring:
  application:
    name: emailservice
  datasource:
    url: jdbc:mysql://localhost:3306/vehiclepasser_email?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update


